
/* CONSTS */

// This package is kinda stupid, just storing a map of ext => mime for all these extensions would be faster and not much heavier

const EXT_SHORT: [string, Set<string>][] = [
  ['image', new Set ([ 'apng', 'bmp', 'cgm', 'emf', 'fits', 'gif', 'heic', 'heif', 'ief', 'jls', 'jp2', 'jpeg', 'jpm', 'jpx', 'jxr', 'ktx', 'png', 'sgi', 't38', 'webp', 'wmf' ])],
  ['application', new Set ([ 'bdoc', 'exi', 'gxf', 'hjson', 'ipfix', 'json', 'json5', 'mbox', 'mxf', 'oda', 'oxps', 'pdf', 'rtf', 'sdp', 'wasm', 'xml', 'yang', 'zip' ])],
  ['text', new Set ([ 'css', 'csv', 'html', 'jade', 'jsx', 'less', 'markdown', 'mdx', 'n3', 'sgml', 'shex', 'slim', 'stylus', 'vcard', 'vtt', 'yaml' ])],
  ['video', new Set ([ '3gpp', 'h261', 'h263', 'h264', 'mj2', 'mp4', 'mpeg', 'webm' ])],
  ['audio', new Set ([ 's3m', 'wav', 'xm' ])],
  ['font', new Set ([ 'otf', 'ttf', 'woff', 'woff2' ])],
  ['message', new Set ([ 'disposition-notification' ])],
  ['model', new Set ([ '3mf', 'stl' ])]
]

const EXT_FULL: [string, Record<string, string>][] = [
  ['application', {
    ez: 'andrew-inset',
    aw: 'applixware',
    atom: 'atom+xml',
    atomcat: 'atomcat+xml',
    atomsvc: 'atomsvc+xml',
    ccxml: 'ccxml+xml',
    cdmia: 'cdmi-capability',
    cdmic: 'cdmi-container',
    cdmid: 'cdmi-domain',
    cdmio: 'cdmi-object',
    cdmiq: 'cdmi-queue',
    cu: 'cu-seeme',
    mpd: 'dash+xml',
    davmount: 'davmount+xml',
    dbk: 'docbook+xml',
    dssc: 'dssc+der',
    xdssc: 'dssc+xml',
    ecma: 'ecmascript',
    emma: 'emma+xml',
    epub: 'epub+zip',
    pfr: 'font-tdpfr',
    geojson: 'geo+json',
    gml: 'gml+xml',
    gpx: 'gpx+xml',
    gz: 'gzip',
    stk: 'hyperstudio',
    ink: 'inkml+xml',
    jar: 'java-archive',
    ser: 'java-serialized-object',
    class: 'java-vm',
    js: 'javascript',
    jsonml: 'jsonml+json',
    jsonld: 'ld+json',
    lostxml: 'lost+xml',
    hqx: 'mac-binhex40',
    cpt: 'mac-compactpro',
    mads: 'mads+xml',
    webmanifest: 'manifest+json',
    mrc: 'marc',
    mrcx: 'marcxml+xml',
    ma: 'mathematica',
    mathml: 'mathml+xml',
    mscml: 'mediaservercontrol+xml',
    metalink: 'metalink+xml',
    meta4: 'metalink4+xml',
    mets: 'mets+xml',
    mods: 'mods+xml',
    m21: 'mp21',
    mp4s: 'mp4',
    doc: 'msword',
    nq: 'n-quads',
    nt: 'n-triples',
    bin: 'octet-stream',
    opf: 'oebps-package+xml',
    ogx: 'ogg',
    omdoc: 'omdoc+xml',
    onetoc: 'onenote',
    xer: 'patch-ops-error+xml',
    pgp: 'pgp-encrypted',
    asc: 'pgp-signature',
    prf: 'pics-rules',
    p10: 'pkcs10',
    p7m: 'pkcs7-mime',
    p7s: 'pkcs7-signature',
    p8: 'pkcs8',
    ac: 'pkix-attr-cert',
    cer: 'pkix-cert',
    crl: 'pkix-crl',
    pkipath: 'pkix-pkipath',
    pki: 'pkixcmp',
    pls: 'pls+xml',
    ai: 'postscript',
    pskcxml: 'pskc+xml',
    raml: 'raml+yaml',
    rdf: 'rdf+xml',
    rif: 'reginfo+xml',
    rnc: 'relax-ng-compact-syntax',
    rl: 'resource-lists+xml',
    rld: 'resource-lists-diff+xml',
    rs: 'rls-services+xml',
    gbr: 'rpki-ghostbusters',
    mft: 'rpki-manifest',
    roa: 'rpki-roa',
    rsd: 'rsd+xml',
    rss: 'rss+xml',
    sbml: 'sbml+xml',
    scq: 'scvp-cv-request',
    scs: 'scvp-cv-response',
    spq: 'scvp-vp-request',
    spp: 'scvp-vp-response',
    setpay: 'set-payment-initiation',
    setreg: 'set-registration-initiation',
    shf: 'shf+xml',
    siv: 'sieve',
    smi: 'smil+xml',
    rq: 'sparql-query',
    srx: 'sparql-results+xml',
    gram: 'srgs',
    grxml: 'srgs+xml',
    sru: 'sru+xml',
    ssdl: 'ssdl+xml',
    ssml: 'ssml+xml',
    tei: 'tei+xml',
    tfi: 'thraud+xml',
    tsd: 'timestamped-data',
    vxml: 'voicexml+xml',
    wgt: 'widget',
    hlp: 'winhlp',
    wsdl: 'wsdl+xml',
    wspolicy: 'wspolicy+xml',
    xaml: 'xaml+xml',
    xdf: 'xcap-diff+xml',
    xenc: 'xenc+xml',
    xhtml: 'xhtml+xml',
    dtd: 'xml-dtd',
    xop: 'xop+xml',
    xpl: 'xproc+xml',
    xslt: 'xslt+xml',
    xspf: 'xspf+xml',
    mxml: 'xv+xml',
    yin: 'yin+xml'
  }],
  ['text', {
    appcache: 'cache-manifest',
    ics: 'calendar',
    coffee: 'coffeescript',
    mml: 'mathml',
    txt: 'plain',
    rtx: 'richtext',
    tsv: 'tab-separated-values',
    t: 'troff',
    ttl: 'turtle',
    uri: 'uri-list'
  }],
  ['image', {
    exr: 'aces',
    drle: 'dicom-rle',
    g3: 'g3fax',
    heics: 'heic-sequence',
    heifs: 'heif-sequence',
    svg: 'svg+xml',
    tif: 'tiff',
    tfx: 'tiff-fx'
  }],
  ['audio', {
    adp: 'adpcm',
    au: 'basic',
    mid: 'midi',
    mp3: 'mpeg',
    m4a: 'mp4',
    mpga: 'mpeg',
    oga: 'ogg',
    sil: 'silk',
    weba: 'webm'
  }],
  ['font', {
    ttc: 'collection'
  }],
  ['model', {
    gltf: 'gltf+json',
    glb: 'gltf-binary',
    igs: 'iges',
    msh: 'mesh',
    wrl: 'vrml',
    x3db: 'x3d+fastinfoset',
    x3dv: 'x3d-vrml',
    x3d: 'x3d+xml'
  }],
  ['video', {
    '3gp': '3gpp',
    '3g2': '3gpp2',
    jpgv: 'jpeg',
    ts: 'mp2t',
    ogv: 'ogg',
    qt: 'quicktime'
  }],
  ['message', {
    u8msg: 'global',
    u8dsn: 'global-delivery-status',
    u8mdn: 'global-disposition-notification',
    u8hdr: 'global-headers',
    eml: 'rfc822'
  }]
];

/* EXPORT */

export {EXT_SHORT, EXT_FULL};
