
/* CONSTS */

// This package is kinda stupid, just storing a map of ext => mime for all these extensions would be faster and not much heavier

const EXT_SHORT: [string, Set<string>][] = [
  ['image', new Set ([ 'apng', 'bmp', 'cgm', 'emf', 'fits', 'gif', 'heic', 'heif', 'ief', 'jls', 'jp2', 'jpeg', 'jpm', 'jpx', 'jxr', 'ktx', 'png', 'sgi', 't38', 'tiff', 'webp', 'wmf' ])],
  ['application', new Set ([ 'bdoc', 'exi', 'gxf', 'hjson', 'ipfix', 'json', 'json5', 'mbox', 'mp21', 'mxf', 'oda', 'oxps', 'pdf', 'rtf', 'sdp', 'sieve', 'wasm', 'xml', 'yang', 'zip' ])],
  ['text', new Set ([ 'css', 'csv', 'html', 'jade', 'jsx', 'less', 'markdown', 'mdx', 'n3', 'sgml', 'shex', 'slim', 'stylus', 'vcard', 'vtt', 'yaml' ])],
  ['video', new Set ([ '3gpp', 'h261', 'h263', 'h264', 'mj2', 'mp4', 'mpeg', 'webm' ])],
  ['audio', new Set ([ 'midi', 'ogg', 's3m', 'wav', 'xm' ])],
  ['font', new Set ([ 'otf', 'ttf', 'woff', 'woff2' ])],
  ['message', new Set ([ 'disposition-notification' ])],
  ['model', new Set ([ '3mf', 'iges', 'mesh', 'stl', 'vrml' ])]
];

const EXT_FULL: [string, Record<string, string>][] = [
  ['application', {
    ac: 'pkix-attr-cert',
    ai: 'postscript',
    asc: 'pgp-signature',
    atom: 'atom+xml',
    atomcat: 'atomcat+xml',
    atomsvc: 'atomsvc+xml',
    aw: 'applixware',
    bin: 'octet-stream',
    bpk: 'octet-stream',
    buffer: 'octet-stream',
    ccxml: 'ccxml+xml',
    cdmia: 'cdmi-capability',
    cdmic: 'cdmi-container',
    cdmid: 'cdmi-domain',
    cdmio: 'cdmi-object',
    cdmiq: 'cdmi-queue',
    cer: 'pkix-cert',
    class: 'java-vm',
    cpt: 'mac-compactpro',
    crl: 'pkix-crl',
    cu: 'cu-seeme',
    davmount: 'davmount+xml',
    dbk: 'docbook+xml',
    deb: 'octet-stream',
    deploy: 'octet-stream',
    dist: 'octet-stream',
    distz: 'octet-stream',
    dll: 'octet-stream',
    dmg: 'octet-stream',
    dms: 'octet-stream',
    doc: 'msword',
    dot: 'msword',
    dssc: 'dssc+der',
    dtd: 'xml-dtd',
    dump: 'octet-stream',
    ear: 'java-archive',
    ecma: 'ecmascript',
    elc: 'octet-stream',
    emma: 'emma+xml',
    eps: 'postscript',
    epub: 'epub+zip',
    es: 'ecmascript',
    exe: 'octet-stream',
    ez: 'andrew-inset',
    gbr: 'rpki-ghostbusters',
    geojson: 'geo+json',
    gml: 'gml+xml',
    gpx: 'gpx+xml',
    gram: 'srgs',
    grxml: 'srgs+xml',
    gz: 'gzip',
    hlp: 'winhlp',
    hqx: 'mac-binhex40',
    img: 'octet-stream',
    ink: 'inkml+xml',
    inkml: 'inkml+xml',
    iso: 'octet-stream',
    jar: 'java-archive',
    js: 'javascript',
    jsonld: 'ld+json',
    jsonml: 'jsonml+json',
    lostxml: 'lost+xml',
    lrf: 'octet-stream',
    m21: 'mp21',
    m4p: 'mp4',
    ma: 'mathematica',
    mads: 'mads+xml',
    map: 'json',
    mar: 'octet-stream',
    mathml: 'mathml+xml',
    mb: 'mathematica',
    meta4: 'metalink4+xml',
    metalink: 'metalink+xml',
    mets: 'mets+xml',
    mft: 'rpki-manifest',
    mjs: 'javascript',
    mods: 'mods+xml',
    mp4s: 'mp4',
    mpd: 'dash+xml',
    mrc: 'marc',
    mrcx: 'marcxml+xml',
    mscml: 'mediaservercontrol+xml',
    msi: 'octet-stream',
    msm: 'octet-stream',
    msp: 'octet-stream',
    mxml: 'xv+xml',
    nb: 'mathematica',
    nq: 'n-quads',
    nt: 'n-triples',
    ogx: 'ogg',
    omdoc: 'omdoc+xml',
    onepkg: 'onenote',
    onetmp: 'onenote',
    onetoc: 'onenote',
    onetoc2: 'onenote',
    opf: 'oebps-package+xml',
    owl: 'rdf+xml',
    p10: 'pkcs10',
    p7c: 'pkcs7-mime',
    p7m: 'pkcs7-mime',
    p7s: 'pkcs7-signature',
    p8: 'pkcs8',
    pfr: 'font-tdpfr',
    pgp: 'pgp-encrypted',
    pkg: 'octet-stream',
    pki: 'pkixcmp',
    pkipath: 'pkix-pkipath',
    pls: 'pls+xml',
    prf: 'pics-rules',
    ps: 'postscript',
    pskcxml: 'pskc+xml',
    raml: 'raml+yaml',
    rdf: 'rdf+xml',
    rif: 'reginfo+xml',
    rl: 'resource-lists+xml',
    rld: 'resource-lists-diff+xml',
    rnc: 'relax-ng-compact-syntax',
    rng: 'xml',
    roa: 'rpki-roa',
    rq: 'sparql-query',
    rs: 'rls-services+xml',
    rsd: 'rsd+xml',
    rss: 'rss+xml',
    sbml: 'sbml+xml',
    scq: 'scvp-cv-request',
    scs: 'scvp-cv-response',
    ser: 'java-serialized-object',
    setpay: 'set-payment-initiation',
    setreg: 'set-registration-initiation',
    shf: 'shf+xml',
    sig: 'pgp-signature',
    siv: 'sieve',
    smi: 'smil+xml',
    smil: 'smil+xml',
    so: 'octet-stream',
    spp: 'scvp-vp-response',
    spq: 'scvp-vp-request',
    sru: 'sru+xml',
    srx: 'sparql-results+xml',
    ssdl: 'ssdl+xml',
    ssml: 'ssml+xml',
    stk: 'hyperstudio',
    tei: 'tei+xml',
    teicorpus: 'tei+xml',
    tfi: 'thraud+xml',
    tsd: 'timestamped-data',
    vxml: 'voicexml+xml',
    war: 'java-archive',
    webmanifest: 'manifest+json',
    wgt: 'widget',
    wsdl: 'wsdl+xml',
    wspolicy: 'wspolicy+xml',
    xaml: 'xaml+xml',
    xdf: 'xcap-diff+xml',
    xdssc: 'dssc+xml',
    xenc: 'xenc+xml',
    xer: 'patch-ops-error+xml',
    xht: 'xhtml+xml',
    xhtml: 'xhtml+xml',
    xhvml: 'xv+xml',
    xop: 'xop+xml',
    xpl: 'xproc+xml',
    xsd: 'xml',
    xsl: 'xml',
    xslt: 'xslt+xml',
    xspf: 'xspf+xml',
    xvm: 'xv+xml',
    xvml: 'xv+xml',
    yin: 'yin+xml',
  }],
  ['text', {
    appcache: 'cache-manifest',
    coffee: 'coffeescript',
    conf: 'plain',
    def: 'plain',
    htm: 'html',
    ics: 'calendar',
    ifb: 'calendar',
    in: 'plain',
    ini: 'plain',
    list: 'plain',
    litcoffee: 'coffeescript',
    log: 'plain',
    man: 'troff',
    manifest: 'cache-manifest',
    md: 'markdown',
    me: 'troff',
    mml: 'mathml',
    ms: 'troff',
    roff: 'troff',
    rtx: 'richtext',
    sgm: 'sgml',
    shtml: 'html',
    slm: 'slim',
    styl: 'stylus',
    t: 'troff',
    text: 'plain',
    tr: 'troff',
    tsv: 'tab-separated-values',
    ttl: 'turtle',
    txt: 'plain',
    uri: 'uri-list',
    uris: 'uri-list',
    urls: 'uri-list',
    yml: 'yaml'
  }],
  ['image', {
    drle: 'dicom-rle',
    exr: 'aces',
    g3: 'g3fax',
    heics: 'heic-sequence',
    heifs: 'heif-sequence',
    jpe: 'jpeg',
    jpf: 'jpx',
    jpg: 'jpeg',
    jpg2: 'jp2',
    svg: 'svg+xml',
    svgz: 'svg+xml',
    tfx: 'tiff-fx',
    tif: 'tiff'
  }],
  ['audio', {
    adp: 'adpcm',
    au: 'basic',
    kar: 'midi',
    m2a: 'mpeg',
    m3a: 'mpeg',
    m4a: 'mp4',
    mid: 'midi',
    mp2: 'mpeg',
    mp2a: 'mpeg',
    mp3: 'mpeg',
    mp4a: 'mp4',
    mpga: 'mpeg',
    oga: 'ogg',
    opus: 'ogg',
    rmi: 'midi',
    sil: 'silk',
    snd: 'basic',
    spx: 'ogg',
    weba: 'webm'
  }],
  ['font', {
    ttc: 'collection'
  }],
  ['model', {
    glb: 'gltf-binary',
    gltf: 'gltf+json',
    igs: 'iges',
    msh: 'mesh',
    silo: 'mesh',
    wrl: 'vrml',
    x3d: 'x3d+xml',
    x3db: 'x3d+fastinfoset',
    x3dv: 'x3d-vrml',
    x3dz: 'x3d+xml'
  }],
  ['video', {
    '3g2': '3gpp2',
    '3gp': '3gpp',
    m1v: 'mpeg',
    m2v: 'mpeg',
    mjp2: 'mj2',
    mov: 'quicktime',
    mp4v: 'mp4',
    mpe: 'mpeg',
    mpg: 'mpeg',
    mpg4: 'mp4',
    jpgv: 'jpeg',
    ogv: 'ogg',
    qt: 'quicktime',
    ts: 'mp2t'
  }],
  ['message', {
    u8msg: 'global',
    u8dsn: 'global-delivery-status',
    u8mdn: 'global-disposition-notification',
    u8hdr: 'global-headers',
    eml: 'rfc822',
    mime: 'rfc822'
  }]
];

/* EXPORT */

export {EXT_SHORT, EXT_FULL};
